<?php $this->headTitle($this->translate('Welcome')) ?>

<div class="container">

    <div class="row">
        <div class="col-md-12">
            <h1 class="h1"><?php echo $this->translate('Welcome') ?></h1>
            <p><?php echo $this->message ?></p>
            <?php $this->placeholder('message')->set($this->message); ?>
            <!--<p><?php echo $this->placeholder('foo'); ?></p>-->
        </div>
    </div>

</div>